#!/bin/bash
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# Fail on error
set -e

if ! state_done WALLET_GET; then
  if test -z "$MTDRWORKSHOP_LOCATION"; then
    echo "ERROR: MTDRWORKSHOP_LOCATION is not set"
    exit
  fi
  if ! test -d "$MTDRWORKSHOP_LOCATION/wallet"; then
    echo "ERROR: wallet folder not found at $MTDRWORKSHOP_LOCATION/wallet"
    exit
  fi
  if ! test -f "$MTDRWORKSHOP_LOCATION/wallet/cwallet.sso"; then
    echo "ERROR: cwallet.sso not found in wallet folder"
    exit
  fi
  if ! test -f "$MTDRWORKSHOP_LOCATION/wallet/tnsnames.ora"; then
    echo "ERROR: tnsnames.ora not found in wallet folder"
    exit
  fi
  state_set_done OBJECT_STORE_BUCKET
  state_set_done WALLET_GET
  state_set_done CWALLET_SSO_OBJECT
  state_set_done CWALLET_SSO_AUTH_URL
fi

if [[ "${USE_EXISTING_WALLET:-0}" == "1" ]]; then
  if test -z "$EXISTING_WALLET_PATH"; then
    echo "ERROR: USE_EXISTING_WALLET is set but EXISTING_WALLET_PATH is empty"
    exit 1
  fi
  cd "$MTDRWORKSHOP_LOCATION"
  mkdir -p wallet
  if test -f "$EXISTING_WALLET_PATH"; then
    if test -n "$WALLET_ZIP_PASSWORD"; then
      unzip -o -P "$WALLET_ZIP_PASSWORD" "$EXISTING_WALLET_PATH" -d "$MTDRWORKSHOP_LOCATION/wallet"
    else
      if ! unzip -o "$EXISTING_WALLET_PATH" -d "$MTDRWORKSHOP_LOCATION/wallet"; then
        echo "ERROR: Wallet zip requires WALLET_ZIP_PASSWORD"
        exit 1
      fi
    fi
  elif test -d "$EXISTING_WALLET_PATH"; then
    cp -R "$EXISTING_WALLET_PATH"/. "$MTDRWORKSHOP_LOCATION/wallet/"
  else
    echo "ERROR: EXISTING_WALLET_PATH not found"
    exit 1
  fi
  state_set_done OBJECT_STORE_BUCKET
  state_set_done WALLET_GET
  state_set_done CWALLET_SSO_OBJECT
  state_set_done CWALLET_SSO_AUTH_URL
fi


# Wait for Order DB OCID
while ! state_done MTDR_DB_OCID; do
  echo "`date`: Waiting for MTDR_DB_OCID"
  sleep 2
done


# Give DB_PASSWORD priority
while ! state_done DB_PASSWORD; do
  echo "Waiting for DB_PASSWORD"
  sleep 5
done


# Create Inventory ATP Bindings
while ! state_done DB_WALLET_SECRET; do
  echo "creating Inventory ATP Bindings"
  cd $MTDRWORKSHOP_LOCATION/wallet
  cat - >sqlnet.ora <<!
WALLET_LOCATION = (SOURCE = (METHOD = file) (METHOD_DATA = (DIRECTORY="/mtdrworkshop/creds")))
SSL_SERVER_DN_MATCH=yes
!
  if kubectl create -f - -n mtdrworkshop; then
    state_set_done DB_WALLET_SECRET
  else
    echo "Error: Failure to create db-wallet-secret.  Retrying..."
    sleep 5
  fi <<!
apiVersion: v1
data:
  README: $(base64 -w0 README)
  cwallet.sso: $(base64 -w0 cwallet.sso)
  ewallet.p12: $(base64 -w0 ewallet.p12)
  keystore.jks: $(base64 -w0 keystore.jks)
  ojdbc.properties: $(base64 -w0 ojdbc.properties)
  sqlnet.ora: $(base64 -w0 sqlnet.ora)
  tnsnames.ora: $(base64 -w0 tnsnames.ora)
  truststore.jks: $(base64 -w0 truststore.jks)
kind: Secret
metadata:
  name: db-wallet-secret
!
  cd $MTDRWORKSHOP_LOCATION
done


# DB Connection Setup
export TNS_ADMIN=$MTDRWORKSHOP_LOCATION/wallet
cat - >$TNS_ADMIN/sqlnet.ora <<!
WALLET_LOCATION = (SOURCE = (METHOD = file) (METHOD_DATA = (DIRECTORY="$TNS_ADMIN")))
SSL_SERVER_DN_MATCH=yes
!
MTDR_DB_SVC="$(state_get MTDR_DB_NAME)_tp"
APP_USER=TODOUSER


# Get DB Password
while true; do
  if DB_PASSWORD=`kubectl get secret dbuser -n mtdrworkshop --template={{.data.dbpassword}} | base64 --decode`; then
    if ! test -z "$DB_PASSWORD"; then
      break
    fi
  fi
  echo "Error: Failed to get DB password.  Retrying..."
  sleep 5
done


# Build application schema and seed data
while ! state_done APP_SCHEMA; do
  echo "creating application schema and seed data"
  SVC=$MTDR_DB_SVC
  sqlplus -s /nolog <<SQL
WHENEVER SQLERROR EXIT 1
connect admin/"$DB_PASSWORD"@$SVC

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER $APP_USER IDENTIFIED BY "$DB_PASSWORD" DEFAULT TABLESPACE data QUOTA UNLIMITED ON data';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN
      RAISE;
    END IF;
END;
/

GRANT CREATE SESSION TO $APP_USER;
GRANT CREATE TABLE TO $APP_USER;
GRANT CREATE VIEW TO $APP_USER;
GRANT CREATE SEQUENCE TO $APP_USER;
GRANT CREATE PROCEDURE TO $APP_USER;
GRANT CREATE TRIGGER TO $APP_USER;
GRANT CREATE TYPE TO $APP_USER;

connect $APP_USER/"$DB_PASSWORD"@$SVC

-- ========================================
-- CHECK IF SCHEMA ALREADY EXISTS
-- If tables exist, skip creation entirely
-- ========================================
DECLARE
  v_count INTEGER := 0;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'ROL';
  IF v_count > 0 THEN
    DBMS_OUTPUT.PUT_LINE('INFO: Schema already exists. Skipping table creation.');
    DBMS_OUTPUT.PUT_LINE('INFO: Database is ready to use.');
  END IF;
END;
/

-- ========================================
-- CREATE TABLES (ONLY IF THEY DO NOT EXIST)
-- ========================================

CREATE TABLE ROL (
    ID_ROL NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255),
    CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL),
    CONSTRAINT UQ_ROL_NOMBRE UNIQUE (NOMBRE)
);

CREATE TABLE EQUIPO (
    ID_EQUIPO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(150) NOT NULL,
    FECHA_CREACION DATE,
    CONSTRAINT PK_EQUIPO PRIMARY KEY (ID_EQUIPO)
);

CREATE TABLE ESTADO_TAREA (
    ID_ESTADO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    ES_FINAL NUMBER(1,0),
    CONSTRAINT PK_ESTADO_TAREA PRIMARY KEY (ID_ESTADO)
);

CREATE TABLE USUARIO (
    ID_USUARIO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(150) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL,
    TELEGRAM_CHAT_ID VARCHAR2(50),
    ACTIVO NUMBER(1,0),
    FECHA_INGRESO DATE,
    MODALIDAD_TRABAJO VARCHAR2(50),
    ID_EQUIPO NUMBER(10),
    ID_ROL NUMBER(10) NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_USUARIO_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_USUARIO_EQUIPO FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO (ID_EQUIPO),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);

CREATE TABLE PROYECTO (
    ID_PROYECTO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(200) NOT NULL,
    DESCRIPCION VARCHAR2(500),
    ESTADO VARCHAR2(50),
    FECHA_INICIO DATE,
    FECHA_FIN_ESTIMADA DATE,
    FECHA_FIN_REAL DATE,
    ID_EQUIPO NUMBER(10),
    CONSTRAINT PK_PROYECTO PRIMARY KEY (ID_PROYECTO),
    CONSTRAINT FK_PROYECTO_EQUIPO FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO (ID_EQUIPO)
);

CREATE TABLE SPRINT (
    ID_SPRINT NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    OBJETIVO VARCHAR2(500),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ID_PROYECTO NUMBER(10) NOT NULL,
    CONSTRAINT PK_SPRINT PRIMARY KEY (ID_SPRINT),
    CONSTRAINT FK_SPRINT_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);

CREATE TABLE USUARIO_PROYECTO (
    ID_USUARIO NUMBER(10) NOT NULL,
    ID_PROYECTO NUMBER(10) NOT NULL,
    ROL_EN_PROYECTO VARCHAR2(100),
    FECHA_ASIGNACION DATE,
    CONSTRAINT PK_USUARIO_PROYECTO PRIMARY KEY (ID_USUARIO, ID_PROYECTO),
    CONSTRAINT FK_UP_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT FK_UP_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);

CREATE TABLE TAREA (
    ID_TAREA NUMBER(10) NOT NULL,
    TITULO VARCHAR2(200) NOT NULL,
    DESCRIPCION VARCHAR2(1000),
    FECHA_CREACION DATE,
    FECHA_FIN_ESTIMADA DATE,
    FECHA_FIN_REAL DATE,
    ESTIMACION_HORAS NUMBER(5,2),
    HORAS_REALES NUMBER(5,2),
    PRIORIDAD VARCHAR2(50),
    ID_USUARIO NUMBER(10),
    ID_ESTADO NUMBER(10) NOT NULL,
    ID_PROYECTO NUMBER(10) NOT NULL,
    ID_SPRINT NUMBER(10),
    CONSTRAINT PK_TAREA PRIMARY KEY (ID_TAREA),
    CONSTRAINT FK_TAREA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT FK_TAREA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TAREA (ID_ESTADO),
    CONSTRAINT FK_TAREA_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_TAREA_SPRINT FOREIGN KEY (ID_SPRINT) REFERENCES SPRINT (ID_SPRINT)
);

CREATE TABLE MENSAJE_CHATBOT (
    ID_MENSAJE NUMBER(10) NOT NULL,
    ID_USUARIO NUMBER(10) NOT NULL,
    TEXTO_MESSAGE VARCHAR2(1000),
    FECHA_ENVIO DATE,
    CONSTRAINT PK_MENSAJE_CHATBOT PRIMARY KEY (ID_MENSAJE),
    CONSTRAINT FK_MSG_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE ACTIVIDAD (
    ID_ACTIVIDAD NUMBER(10) NOT NULL,
    DESCRIPCION VARCHAR2(255) NOT NULL,
    FECHA DATE,
    TIPO_ACTIVIDAD VARCHAR2(100),
    ID_USUARIO NUMBER(10) NOT NULL,
    CONSTRAINT PK_ACTIVIDAD PRIMARY KEY (ID_ACTIVIDAD),
    CONSTRAINT FK_ACT_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE KPI (
    ID_KPI NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(150) NOT NULL,
    DESCRIPCION VARCHAR2(255),
    FORMULA_DESCRIPTIVA VARCHAR2(255),
    NIVEL_APLICACION VARCHAR2(100),
    ID_PROYECTO NUMBER(10) NOT NULL,
    CONSTRAINT PK_KPI PRIMARY KEY (ID_KPI),
    CONSTRAINT FK_KPI_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);

CREATE TABLE RESULTADO_KPI (
    ID_RESULTADO NUMBER(10) NOT NULL,
    VALOR NUMBER(10,2) NOT NULL,
    FECHA_CALCULO DATE,
    ID_KPI NUMBER(10) NOT NULL,
    CONSTRAINT PK_RESULTADO_KPI PRIMARY KEY (ID_RESULTADO),
    CONSTRAINT FK_RESULTADO_KPI FOREIGN KEY (ID_KPI) REFERENCES KPI (ID_KPI)
);

CREATE INDEX IDX_USUARIO_ROL ON USUARIO (ID_ROL);
CREATE INDEX IDX_USUARIO_EQUIPO ON USUARIO (ID_EQUIPO);
CREATE INDEX IDX_PROYECTO_EQUIPO ON PROYECTO (ID_EQUIPO);
CREATE INDEX IDX_SPRINT_PROYECTO ON SPRINT (ID_PROYECTO);
CREATE INDEX IDX_UP_PROYECTO ON USUARIO_PROYECTO (ID_PROYECTO);
CREATE INDEX IDX_UP_USUARIO ON USUARIO_PROYECTO (ID_USUARIO);
CREATE INDEX IDX_TAREA_USUARIO ON TAREA (ID_USUARIO);
CREATE INDEX IDX_TAREA_ESTADO ON TAREA (ID_ESTADO);
CREATE INDEX IDX_TAREA_PROYECTO ON TAREA (ID_PROYECTO);
CREATE INDEX IDX_TAREA_SPRINT ON TAREA (ID_SPRINT);
CREATE INDEX IDX_MSG_USUARIO ON MENSAJE_CHATBOT (ID_USUARIO);
CREATE INDEX IDX_ACT_USUARIO ON ACTIVIDAD (ID_USUARIO);
CREATE INDEX IDX_KPI_PROYECTO ON KPI (ID_PROYECTO);
CREATE INDEX IDX_RESULTADO_KPI ON RESULTADO_KPI (ID_KPI);

INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION) VALUES (1, 'PM', 'Project manager');
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION) VALUES (2, 'DEVELOPER', 'Developer');
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION) VALUES (3, 'QA', 'Quality assurance');

INSERT INTO EQUIPO (ID_EQUIPO, NOMBRE, FECHA_CREACION) VALUES (1, 'Equipo Principal', DATE '2026-04-16');

INSERT INTO ESTADO_TAREA (ID_ESTADO, NOMBRE, ES_FINAL) VALUES (1, 'TODO', 0);
INSERT INTO ESTADO_TAREA (ID_ESTADO, NOMBRE, ES_FINAL) VALUES (2, 'EN_PROGRESO', 0);
INSERT INTO ESTADO_TAREA (ID_ESTADO, NOMBRE, ES_FINAL) VALUES (3, 'TERMINADA', 1);
INSERT INTO ESTADO_TAREA (ID_ESTADO, NOMBRE, ES_FINAL) VALUES (4, 'BLOQUEADA', 0);

INSERT INTO USUARIO (ID_USUARIO, NOMBRE, EMAIL, TELEGRAM_CHAT_ID, ACTIVO, FECHA_INGRESO, MODALIDAD_TRABAJO, ID_EQUIPO, ID_ROL)
VALUES (1, 'Project Manager', 'pm@empresa.com', NULL, 1, DATE '2026-04-16', 'Hibrido', 1, 1);
INSERT INTO USUARIO (ID_USUARIO, NOMBRE, EMAIL, TELEGRAM_CHAT_ID, ACTIVO, FECHA_INGRESO, MODALIDAD_TRABAJO, ID_EQUIPO, ID_ROL)
VALUES (2, 'Developer 1', 'dev1@empresa.com', NULL, 1, DATE '2026-04-16', 'Remoto', 1, 2);
INSERT INTO USUARIO (ID_USUARIO, NOMBRE, EMAIL, TELEGRAM_CHAT_ID, ACTIVO, FECHA_INGRESO, MODALIDAD_TRABAJO, ID_EQUIPO, ID_ROL)
VALUES (3, 'Developer 2', 'dev2@empresa.com', NULL, 1, DATE '2026-04-16', 'Remoto', 1, 2);

INSERT INTO PROYECTO (ID_PROYECTO, NOMBRE, DESCRIPCION, ESTADO, FECHA_INICIO, FECHA_FIN_ESTIMADA, FECHA_FIN_REAL, ID_EQUIPO)
VALUES (1, 'Proyecto Principal', 'Proyecto base del dashboard', 'ACTIVO', DATE '2026-04-16', DATE '2026-12-31', NULL, 1);

INSERT INTO SPRINT (ID_SPRINT, NOMBRE, OBJETIVO, FECHA_INICIO, FECHA_FIN, ID_PROYECTO)
VALUES (1, 'Sprint 1', 'Sprint inicial', DATE '2026-04-16', DATE '2026-04-30', 1);

INSERT INTO USUARIO_PROYECTO (ID_USUARIO, ID_PROYECTO, ROL_EN_PROYECTO, FECHA_ASIGNACION) VALUES (1, 1, 'PM', DATE '2026-04-16');
INSERT INTO USUARIO_PROYECTO (ID_USUARIO, ID_PROYECTO, ROL_EN_PROYECTO, FECHA_ASIGNACION) VALUES (2, 1, 'DEV', DATE '2026-04-16');
INSERT INTO USUARIO_PROYECTO (ID_USUARIO, ID_PROYECTO, ROL_EN_PROYECTO, FECHA_ASIGNACION) VALUES (3, 1, 'DEV', DATE '2026-04-16');

INSERT INTO TAREA (ID_TAREA, TITULO, DESCRIPCION, FECHA_CREACION, FECHA_FIN_ESTIMADA, FECHA_FIN_REAL, ESTIMACION_HORAS, HORAS_REALES, PRIORIDAD, ID_USUARIO, ID_ESTADO, ID_PROYECTO, ID_SPRINT)
VALUES (1, 'Definir flujo principal', 'Tarea de ejemplo 1', DATE '2026-04-16', DATE '2026-04-20', DATE '2026-04-19', 6, 5.5, 'ALTA', 2, 3, 1, 1);
INSERT INTO TAREA (ID_TAREA, TITULO, DESCRIPCION, FECHA_CREACION, FECHA_FIN_ESTIMADA, FECHA_FIN_REAL, ESTIMACION_HORAS, HORAS_REALES, PRIORIDAD, ID_USUARIO, ID_ESTADO, ID_PROYECTO, ID_SPRINT)
VALUES (2, 'Ajustar UI del dashboard', 'Tarea de ejemplo 2', DATE '2026-04-16', DATE '2026-04-22', NULL, 4, 3.5, 'MEDIA', 3, 2, 1, 1);
INSERT INTO TAREA (ID_TAREA, TITULO, DESCRIPCION, FECHA_CREACION, FECHA_FIN_ESTIMADA, FECHA_FIN_REAL, ESTIMACION_HORAS, HORAS_REALES, PRIORIDAD, ID_USUARIO, ID_ESTADO, ID_PROYECTO, ID_SPRINT)
VALUES (3, 'Validar KPI de tareas', 'Tarea de ejemplo 3', DATE '2026-04-16', DATE '2026-04-25', NULL, 8, NULL, 'ALTA', 2, 1, 1, 1);

INSERT INTO MENSAJE_CHATBOT (ID_MENSAJE, ID_USUARIO, TEXTO_MESSAGE, FECHA_ENVIO)
VALUES (1, 1, 'Mensaje de ejemplo', DATE '2026-04-16');

INSERT INTO ACTIVIDAD (ID_ACTIVIDAD, DESCRIPCION, FECHA, TIPO_ACTIVIDAD, ID_USUARIO)
VALUES (1, 'Creación inicial del proyecto', DATE '2026-04-16', 'SETUP', 1);

INSERT INTO KPI (ID_KPI, NOMBRE, DESCRIPCION, FORMULA_DESCRIPTIVA, NIVEL_APLICACION, ID_PROYECTO)
VALUES (1, 'Tareas terminadas por usuario y sprint', 'Conteo de tareas finalizadas por usuario y sprint', 'COUNT(tareas donde estado final)', 'SPRINT', 1);
INSERT INTO KPI (ID_KPI, NOMBRE, DESCRIPCION, FORMULA_DESCRIPTIVA, NIVEL_APLICACION, ID_PROYECTO)
VALUES (2, 'Horas reales por usuario y sprint', 'Suma de horas reales por usuario y sprint', 'SUM(HORAS_REALES)', 'SPRINT', 1);

INSERT INTO RESULTADO_KPI (ID_RESULTADO, VALOR, FECHA_CALCULO, ID_KPI) VALUES (1, 2, DATE '2026-04-16', 1);
INSERT INTO RESULTADO_KPI (ID_RESULTADO, VALOR, FECHA_CALCULO, ID_KPI) VALUES (2, 9.0, DATE '2026-04-16', 2);

COMMIT;
EXIT;
SQL
  state_set_done APP_SCHEMA
  echo "finished connecting to database and creating schema"
done
# DB Setup Done
state_set_done DB_SETUP

# Create sequence for TAREA if it doesn't exist (idempotent)
cat > create_seq_tarea.sql <<'SQL'
DECLARE
  cnt INTEGER := 0;
BEGIN
  SELECT COUNT(*) INTO cnt FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_TAREA';
  IF cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TAREA START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;
END;
/
SQL

sqlplus -s ${DB_USER}/${DB_PASSWORD}@${DB_CONN} @create_seq_tarea.sql
rm -f create_seq_tarea.sql