CREATE TABLE APP_CONFIG (
    CONFIG_KEY VARCHAR2(100),
    CONFIG_VALUE VARCHAR2(500),
    PRIMARY KEY (CONFIG_KEY)
);

INSERT INTO APP_CONFIG (CONFIG_KEY, CONFIG_VALUE) VALUES ('sprint_count', '3');
