spring.application.name=MyTodoList


driver_class_name=${DRIVER_CLASS_NAME:oracle.jdbc.OracleDriver}
db_user=${DB_USER:TODOUSER}
dbpassword=${DB_PASSWORD:None00010001}
db_url=${DB_URL:jdbc:oracle:thin:@reacttodofpoyo_tp?TNS_ADMIN=./wallet}

telegram.bot.token=${TELEGRAM_BOT_TOKEN:8269682140:AAHkuzZL5JLPQCLsWOe142TGeJ1K-MY6kRM}

deepseek.api.key=${DEEPSEEK_API_KEY:dummy}
deepseek.api.url=${DEEPSEEK_API_URL:https://api.deepseek.com/v1/chat/completions}

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false



logging.level.org.hibernate.SQL=INFO

