package com.springboot.MyTodoList.model;

import java.util.List;

/**
 * Response body for POST /ai/suggest-tasks
 */
public class TaskSuggestionResponse {

    /** Natural language suggestion generated by Gemini */
    private String sugerencia;

    /** The top similar tasks retrieved from Oracle vector search (raw context) */
    private List<TaskSearchResult> tareasEncontradas;

    public TaskSuggestionResponse() {}

    public TaskSuggestionResponse(String sugerencia, List<TaskSearchResult> tareasEncontradas) {
        this.sugerencia = sugerencia;
        this.tareasEncontradas = tareasEncontradas;
    }

    public String getSugerencia() { return sugerencia; }
    public void setSugerencia(String sugerencia) { this.sugerencia = sugerencia; }

    public List<TaskSearchResult> getTareasEncontradas() { return tareasEncontradas; }
    public void setTareasEncontradas(List<TaskSearchResult> tareasEncontradas) {
        this.tareasEncontradas = tareasEncontradas;
    }
}
